sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - gettext
    - python-dev
    - zlib1g-dev
    - libpq-dev xvfb
    - libtiff4-dev
    - libjpeg8-dev
    - libfreetype6-dev
    - liblcms1-dev
    - libwebp-dev
    - graphviz-dev
    - python-setuptools
    - python3-dev
    - python-virtualenv
    - python-pip
    - firefox
    - automake
    - libtool
    - libreadline6
    - libreadline6-dev
    - libreadline-dev
    - libsqlite3-dev
    - libxml2
    - libxml2-dev
    - libssl-dev
    - libbz2-dev
    - wget
    - curl
    - llvm
language: python
python:
  - "3.6"
cache:
  - apt
  - pip
install:
  - pip install -r requirements/local.txt
# command to run tests
script:
  - python manage.py makemigrations account
  - python manage.py makemigrations
  - python manage.py migrate
  - pytest # or py.test for Python versions 3.5 and below
